version: '3.4'
services:
  influxdb:
    image: influxdb:1.4
    ports:
      - "8086:8086"
    volumes:
      - "./data/influxdb:/var/lib/influxdb"


  mtr_monitor:
    build: .
    volumes:
      - "./mtr-monitor:/mtr-monitor"
    links:
      - influxdb


  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    links:
      - influxdb
