{
 "title": "MTR Monitor",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "host", "label": "Target host", "query": "show measurements" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "gauge",
   "description": "$host 14d SLA",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "repeat": "host",
   "targets": [
    {
     "alias": "$m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT 100-sum(\"lost\")/sum(\"snt\")*100 FROM (SELECT min(\"loss\")*mean(\"snt\")/100 as lost, mean(\"snt\") as snt FROM /^$host$/ WHERE time > now() - 1d GROUP BY time(40s) fill(null))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SLA",
   "type": "graph",
   "description": "Plot of minimum value of loss % for granulation set in grafana.\n\nMinimum value displays the true packet loss on a selected route",
   "gridPos": { "h": 9, "w": 22, "x": 2, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT 100-sum(\"lost\")/sum(\"snt\")*100 FROM (SELECT min(\"loss\")*mean(\"snt\")/100 as lost, mean(\"snt\") as snt FROM /^$host$/ WHERE $timeFilter GROUP BY time(40s) fill(null)) GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "description": "$host 14d SLA",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "targets": [
    {
     "alias": "$m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT 100-sum(\"lost\")/sum(\"snt\")*100 FROM (SELECT min(\"loss\")*mean(\"snt\")/100 as lost, mean(\"snt\") as snt FROM /^$host$/ WHERE time > now() - 1d GROUP BY time(40s) fill(null))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "description": "$host 14d SLA",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 7 },
   "targets": [
    {
     "alias": "$m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT 100-sum(\"lost\")/sum(\"snt\")*100 FROM (SELECT min(\"loss\")*mean(\"snt\")/100 as lost, mean(\"snt\") as snt FROM /^$host$/ WHERE time > now() - 1d GROUP BY time(40s) fill(null))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "description": "$host 14d SLA",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 10 },
   "targets": [
    {
     "alias": "$m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT 100-sum(\"lost\")/sum(\"snt\")*100 FROM (SELECT min(\"loss\")*mean(\"snt\")/100 as lost, mean(\"snt\") as snt FROM /^$host$/ WHERE time > now() - 1d GROUP BY time(40s) fill(null))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Min loss for all hosts",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "percent", "label": "Packet loss" }
   ],
   "targets": [
    {
     "alias": "$m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$host$/",
     "query": "SELECT max(\"loss\") FROM (SELECT min(\"loss\") as loss FROM /^$host$/ WHERE $timeFilter GROUP BY time(40s) fill(null)) GROUP BY time($__interval) fill(none)\n\n",
     "select": [
      [
       { "params": [ "loss" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "hop", "operator": "<>", "value": "01-???" },
      { "condition": "AND", "key": "hop", "operator": "<>", "value": "01-_gateway" },
      {
       "condition": "AND",
       "key": "hop",
       "operator": "<>",
       "value": "02-89-72-16-1.dynamic.chello.pl"
      },
      { "condition": "AND", "key": "hop", "operator": "<>", "value": "02-???" }
     ]
    }
   ]
  },
  {
   "title": "Median ping",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "ms", "label": "Medium ping" }
   ],
   "targets": [
    {
     "alias": "$m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$host$/",
     "query": "SELECT mean(\"loss\") FROM \"8.8.8.8\" WHERE (\"hop\" <> '01-???' AND \"hop\" <> '01-_gateway' AND \"hop\" <> '02-89-72-16-1.dynamic.chello.pl' AND \"hop\" <> '02-???') AND $timeFilter GROUP BY time(1s) fill(none)",
     "select": [
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Details for $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 }, "repeat": "host" },
  {
   "title": "Median MTR",
   "type": "graph",
   "description": "Median MTR for hops from 3rd, because ISPs tend to cut off ICMP protocol in their servers - so the data isn't reliable for the first two hops.",
   "gridPos": { "h": 11, "w": 14, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "percent", "label": "Loss per host" }
   ],
   "targets": [
    {
     "alias": "$tag_hop",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hop" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$host$/",
     "query": "SELECT median(\"loss\") FROM /^$host$/ WHERE (\"hop\" !~ /^01-.*/ AND \"hop\" !~ /^02-.*/) AND $timeFilter GROUP BY time($__interval), \"hop\" fill(null)",
     "select": [
      [
       { "params": [ "loss" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "hop", "operator": "<>", "value": "01-???" },
      { "condition": "AND", "key": "hop", "operator": "<>", "value": "02-???" },
      { "condition": "AND", "key": "hop", "operator": "<>", "value": "01-_gateway" },
      {
       "condition": "AND",
       "key": "hop",
       "operator": "<>",
       "value": "02-89-72-16-1.dynamic.chello.pl"
      },
      { "condition": "AND", "key": "hop", "operator": "<>", "value": "02-_gateway" }
     ]
    }
   ]
  },
  {
   "title": "Median loss",
   "type": "graph",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 26 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_hop",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hop" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$host$/",
     "select": [
      [
       { "params": [ "loss" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "hop", "operator": "<>", "value": "01-???" },
      { "condition": "AND", "key": "hop", "operator": "<>", "value": "02-???" }
     ]
    }
   ]
  },
  { "title": "Details for $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Median MTR",
   "type": "graph",
   "description": "Median MTR for hops from 3rd, because ISPs tend to cut off ICMP protocol in their servers - so the data isn't reliable for the first two hops.",
   "gridPos": { "h": 11, "w": 14, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "percent", "label": "Loss per host" }
   ],
   "targets": [
    {
     "alias": "$tag_hop",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hop" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$host$/",
     "query": "SELECT median(\"loss\") FROM /^$host$/ WHERE (\"hop\" !~ /^01-.*/ AND \"hop\" !~ /^02-.*/) AND $timeFilter GROUP BY time($__interval), \"hop\" fill(null)",
     "select": [
      [
       { "params": [ "loss" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "hop", "operator": "<>", "value": "01-???" },
      { "condition": "AND", "key": "hop", "operator": "<>", "value": "02-???" },
      { "condition": "AND", "key": "hop", "operator": "<>", "value": "01-_gateway" },
      {
       "condition": "AND",
       "key": "hop",
       "operator": "<>",
       "value": "02-89-72-16-1.dynamic.chello.pl"
      },
      { "condition": "AND", "key": "hop", "operator": "<>", "value": "02-_gateway" }
     ]
    }
   ]
  },
  {
   "title": "Median loss",
   "type": "graph",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 38 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_hop",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hop" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$host$/",
     "select": [
      [
       { "params": [ "loss" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "hop", "operator": "<>", "value": "01-???" },
      { "condition": "AND", "key": "hop", "operator": "<>", "value": "02-???" }
     ]
    }
   ]
  },
  { "title": "Details for $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Median MTR",
   "type": "graph",
   "description": "Median MTR for hops from 3rd, because ISPs tend to cut off ICMP protocol in their servers - so the data isn't reliable for the first two hops.",
   "gridPos": { "h": 11, "w": 14, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "percent", "label": "Loss per host" }
   ],
   "targets": [
    {
     "alias": "$tag_hop",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hop" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$host$/",
     "query": "SELECT median(\"loss\") FROM /^$host$/ WHERE (\"hop\" !~ /^01-.*/ AND \"hop\" !~ /^02-.*/) AND $timeFilter GROUP BY time($__interval), \"hop\" fill(null)",
     "select": [
      [
       { "params": [ "loss" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "hop", "operator": "<>", "value": "01-???" },
      { "condition": "AND", "key": "hop", "operator": "<>", "value": "02-???" },
      { "condition": "AND", "key": "hop", "operator": "<>", "value": "01-_gateway" },
      {
       "condition": "AND",
       "key": "hop",
       "operator": "<>",
       "value": "02-89-72-16-1.dynamic.chello.pl"
      },
      { "condition": "AND", "key": "hop", "operator": "<>", "value": "02-_gateway" }
     ]
    }
   ]
  },
  {
   "title": "Median loss",
   "type": "graph",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 50 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_hop",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hop" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$host$/",
     "select": [
      [
       { "params": [ "loss" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "hop", "operator": "<>", "value": "01-???" },
      { "condition": "AND", "key": "hop", "operator": "<>", "value": "02-???" }
     ]
    }
   ]
  },
  { "title": "Details for $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Median MTR",
   "type": "graph",
   "description": "Median MTR for hops from 3rd, because ISPs tend to cut off ICMP protocol in their servers - so the data isn't reliable for the first two hops.",
   "gridPos": { "h": 11, "w": 14, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "percent", "label": "Loss per host" }
   ],
   "targets": [
    {
     "alias": "$tag_hop",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hop" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$host$/",
     "query": "SELECT median(\"loss\") FROM /^$host$/ WHERE (\"hop\" !~ /^01-.*/ AND \"hop\" !~ /^02-.*/) AND $timeFilter GROUP BY time($__interval), \"hop\" fill(null)",
     "select": [
      [
       { "params": [ "loss" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "hop", "operator": "<>", "value": "01-???" },
      { "condition": "AND", "key": "hop", "operator": "<>", "value": "02-???" },
      { "condition": "AND", "key": "hop", "operator": "<>", "value": "01-_gateway" },
      {
       "condition": "AND",
       "key": "hop",
       "operator": "<>",
       "value": "02-89-72-16-1.dynamic.chello.pl"
      },
      { "condition": "AND", "key": "hop", "operator": "<>", "value": "02-_gateway" }
     ]
    }
   ]
  },
  {
   "title": "Median loss",
   "type": "graph",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 62 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_hop",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hop" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$host$/",
     "select": [
      [
       { "params": [ "loss" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "hop", "operator": "<>", "value": "01-???" },
      { "condition": "AND", "key": "hop", "operator": "<>", "value": "02-???" }
     ]
    }
   ]
  }
 ]
}